name: Process Marine Data and Deploy Static Site

on:
  push:
    branches: [main, original]
  pull_request:
    branches: [main, original]
  workflow_dispatch: # Allow manual triggering

jobs:
  process-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl geopandas shapely

      - name: Check if marine.xlsx exists
        run: |
          if [ -f "marine.xlsx" ]; then
            echo "marine.xlsx found"
            ls -la marine.xlsx
          else
            echo "marine.xlsx not found, checking uploads folder"
            # Check for existing marine files in uploads folder
            if [ -f "uploads/20250727_094245_marine.xlsx" ]; then
              echo "Using existing marine file from uploads"
              cp uploads/20250727_094245_marine.xlsx marine.xlsx
            else
              echo "No marine data found. Please add marine.xlsx to repository root or uploads folder."
              exit 1
            fi
          fi

      - name: Run actual classification script
        run: |
          echo "Running classification script..."
          python script.py

      - name: Commit and push processed files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output.xlsx
          git add index.html
          # Only commit if there are changes
          git diff --staged --quiet || git commit -m "Update processed marine data and website [skip ci]"
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed-marine-data
          path: |
            output.xlsx
            index.html
